CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  points INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS photos (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  "imageUrl" TEXT NOT NULL,
  memo TEXT NULL,
  is_favorite BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS items (
  id SERIAL PRIMARY KEY,
  name VARCHAR(80) NOT NULL UNIQUE,
  emoji VARCHAR(16) NOT NULL,
  price INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS decorations (
  id SERIAL PRIMARY KEY,
  photo_id INTEGER NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
  item_id INTEGER NOT NULL REFERENCES items(id),
  x DOUBLE PRECISION NOT NULL DEFAULT 0,
  y DOUBLE PRECISION NOT NULL DEFAULT 0,
  scale DOUBLE PRECISION NOT NULL DEFAULT 1,
  rotation DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO items (name, emoji, price)
VALUES
  ('하트', '💖', 10),
  ('별', '⭐', 15),
  ('리본', '🎀', 20),
  ('꽃', '🌸', 25),
  ('좋아요', '👍', 10),
  ('백점', '💯', 30),
  ('똥', '💩', 5),
  ('블랙하트', '🖤', 10)
ON CONFLICT (name) DO NOTHING;
